# Generated by Django 3.1.3 on 2020-11-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('premiere', models.IntegerField(default=2000)),
                ('image', models.URLField(help_text='De imdb mismo')),
                ('summary', models.TextField(help_text='Descripción corta')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
