# Generated by Django 3.1.4 on 2020-12-01 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_filmfavorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmFavorite',
            new_name='FavoriteFilm',
        ),
        migrations.AddField(
            model_name='film',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
